### ISSUE TITLE
Socialscan failure - BreachDirectory showing no data after API key entered

### ISSUE THREAD

**Issue by opticoax747** [alpkeskin/mosint#14]
xxxxxxxxxxxxxxx@gmail.com Use?
ERROR:asyncio:SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f09f0116278>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

**Comment by opticoax747** [comment]
Password Leaks:
[-] Error!

**Comment by opticoax747** [comment]
Maybe cloudflare as my breachdirectory api monitoring is showing

"x-powered-by":
 
"PHP/7.4.27"
"cf-ray":
 
"6d7af8b0aa0f38c1-VIE"
"expect-ct":
 
"max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""
"x-ratelimit-requests-remaining":
 
"46"
"report-to":
 
"{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=Xr1HiHdVCwHT464jDwI1wGqvFOdUNkXRpEHKyn3Ozm0dOGdzkHZRR9URsHSOcT8yAUrFpVRm8GmDaZ8%2Bm8B3WW9d6ySWAV%2Bqo1IyY33J9oUCzxC%2FHH6%2BO9ZeyqN9B1ZQy2dfgYNZ"}],"group":"cf-nel","max_age":604800}"
"strict-transport-security":
 
"max-age=63072000; includeSubDomains"
"x-ratelimit-requests-reset":
 
"2418985"
"x-rapidapi-version":
 
"1.2.8"
"x-turbo-charged-by":
 
"LiteSpeed"
"transfer-encoding":
 
"chunked"
"content-type":
 
"application/json"
"connection":
 
"close"
"nel":
 
"{"success_fraction":0,"report_to":"cf-nel","max_age":604800}"
"x-frame-options":
 
"SAMEORIGIN"

**Comment by alpkeskin** [comment]
I think the problem is with your `python3` version or the libraries you are using. You can update to the latest versions. It's also the first time I see the **SSL** error. It may be related to your computer's network settings.
