### ISSUE TITLE
Some password leaks results don't work in 2.1 but still work in 2.0

### ISSUE THREAD

**Issue by Getsumi3** [alpkeskin/mosint#18]
Hello

After updating to version 2.1 I can't get some password leaks results that are available in 2.0

2.0 password leaks output 
![image](https://user-images.githubusercontent.com/20124129/166661683-2f643505-e9c7-4bbd-b726-117ec2840b61.png)

2.1 password leaks output
![image](https://user-images.githubusercontent.com/20124129/166661731-de517e8e-5575-42ac-962c-5b57e6845a51.png)

**Comment by alpkeskin** [comment]
This error is weird because I just tested it with a few emails and it worked fine. Can you send me a sample email address? my email: `0n1co@protonmail.com`

**Comment by Getsumi3** [comment]
In the above examples I used this email: `vipua2@rambler.ru`

**Comment by alpkeskin** [comment]
My input:
`go run . -e vipua2@rambler.ru -leaks`
Output (breachdirectory):
```
Password Leaks:
|- Tunngle.net
|- Rubukkit.org
|-- vere***** ✔
|- Tunngle.net
|- ArmorGames.com
|-- 8888**** ✔
|-- qwe8***** ✔
|- Twitter.com
|-- 8888** ✔
|-- 2919**** ✔
```

Can you try again?

**Comment by Getsumi3** [comment]
Sorry for a late reply. 
I've just tried again and it actually worked. 

Have no idea what was the problem.
