### ISSUE TITLE
How to solve this issue

### ISSUE THREAD

**Issue by adfrank99** [alpkeskin/mosint#19]
When I try to run a scan I receive the following error.  How can I fix this?  Thank you
anic: exec: "python3": executable file not found in %PATH%

goroutine 1 [running]:
main/modules.Runner({0xc0000ae078, 0x16}, {0x155109d?, 0x0?})
        C:/Users/User 2/mosint/modules/Core.go:42 +0x215
main.main()
        C:/Users/User 2/mosint/main.go:258 +0xb86
exit status 2

**Comment by alpkeskin** [comment]
Is python3 installed on your computer?

**Comment by alpkeskin** [comment]
Either python3 is not installed on your computer or there is no python3 in your **PATH**.  

Check this link:
https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages
