### ISSUE TITLE
Add Facebook

### ISSUE THREAD

**Issue by fisicorj** [alpkeskin/mosint#21]
Is it possible to activate the social network search also on facebook?

I'm looking at the code to understand your logic trying to make this change, but if you can add it, it would be very good.

**Comment by alpkeskin** [comment]
Hi, I've been working on a new version for a while. I will publish the new version on **June 8th**. I can add Facebook if i can :) Also, I'm developing a tool to just scan social media: [wau](https://github.com/alpkeskin/wau)
