### ISSUE TITLE
cannto find package

### ISSUE THREAD

**Issue by cyghtinc** [alpkeskin/mosint#22]
Hi,

How can I resolve this issue: (tested on ubuntu18)

main.go:17:2: cannot find package "github.com/dimiro1/banner" in any of:
	/usr/lib/go-1.10/src/github.com/dimiro1/banner (from $GOROOT)
	/home/forensics/go/src/github.com/dimiro1/banner (from $GOPATH)
main.go:18:2: cannot find package "github.com/fatih/color" in any of:
	/usr/lib/go-1.10/src/github.com/fatih/color (from $GOROOT)
	/home/forensics/go/src/github.com/fatih/color (from $GOPATH)
main.go:19:2: cannot find package "github.com/mattn/go-colorable" in any of:
	/usr/lib/go-1.10/src/github.com/mattn/go-colorable (from $GOROOT)
	/home/forensics/go/src/github.com/mattn/go-colorable (from $GOPATH)
main.go:20:2: cannot find package "github.com/olekukonko/tablewriter" in any of:
	/usr/lib/go-1.10/src/github.com/olekukonko/tablewriter (from $GOROOT)
	/home/forensics/go/src/github.com/olekukonko/tablewriter (from $GOPATH)
main.go:21:2: cannot find package "github.com/schollz/progressbar/v3" in any of:
	/usr/lib/go-1.10/src/github.com/schollz/progressbar/v3 (from $GOROOT)
	/home/forensics/go/src/github.com/schollz/progressbar/v3 (from $GOPATH)
main.go:12:2: cannot find package "main/modules" in any of:
	/usr/lib/go-1.10/src/main/modules (from $GOROOT)
	/home/forensics/go/src/main/modules (from $GOPATH)

**Comment by alpkeskin** [comment]
Can you run `go mod tidy` ?

**Comment by B1gM8c** [comment]
The same error:
`
main/modules.doRequest({0xc001c491d0, 0x45}, {0xa64dfc, 0x6})
        /home/fancypig/Desktop/mosint/modules/ThreatCrowd.go:31 +0x705
main/modules.RelatedEmails({0x7fffb91223c5?, 0xd?})
        /home/fancypig/Desktop/mosint/modules/ThreatCrowd.go:59 +0x65
main.main()
        /home/fancypig/Desktop/mosint/main.go:261 +0xbcd
exit status 2
`

**Comment by alpkeskin** [comment]
Hi, new version released 🚀
