### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by u11kumar** [alpkeskin/mosint#24]
mosinting  36% |███████████                     | (36/100, 7 it/s) [8s:9s]panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main/modules.doRequest({0xc000e30410, 0x4f}, {0xa6740a, 0x7})
	/home/user/Downloads/important/mosint/modules/ThreatCrowd.go:28 +0x670
main/modules.RelatedDomains(...)
	/home/user/Downloads/important/mosint/modules/ThreatCrowd.go:52
main.main()
	/home/user/Downloads/important/mosint/main.go:263 +0xc2b
exit status 2

**Comment by crossdefalt** [comment]
i had the same issue but it got fixed idk how
