### ISSUE TITLE
Python not found error on windows 11 machine

### ISSUE THREAD

**Issue by MagicScorpion** [alpkeskin/mosint#26]
D:\Bug_Bounty\mosint>go run main.go -e prathamesh77@gmail.com -all
 

```
>                              _           _
>     _ __ ___     ___    ___  (_)  _ __   | |_
>    | '_ ` _ \   / _ \  / __| | | | '_ \  | __|
>    | | | | | | | (_) | \__ \ | | | | | | | |_
>    |_| |_| |_|  \___/  |___/ |_| |_| |_|  \__|
> 
>    v2.1
>    https://github.com/alpkeskin/
>    Now: Monday, 18 Jul 2022
> 
> mosinting  20% |███████████████                                                             | (20/100, 21 it/s) [0s:3s]panic: exec: "python3": executable file not found in %PATH%
> 
> goroutine 1 [running]:
> main/modules.Runner({0xc0000200d0, 0x10}, {0xf7219d?, 0x0?})
>         D:/Bug_Bounty/mosint/modules/Core.go:42 +0x215
> main.main()
>         D:/Bug_Bounty/mosint/main.go:258 +0xb86
> exit status 2
```

D:\Bug_Bounty\mosint>echo %path%
`C:\Python3;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;D:\Android_Hacking\platform-tools_r33.0.2-windows\platform-tools;C:\Program Files\Go\bin;C:\Users\magic\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\magic\AppData\Local\Programs\Python\Python310\;C:\Users\magic\AppData\Local\Programs\Python\Python3\Scripts\;C:\Users\magic\AppData\Local\Programs\Python\Python3\;C:\Users\magic\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\magic\AppData\Local\Programs\Python\Python39\;C:\Users\magic\AppData\Local\Microsoft\WindowsApps;C:\Users\magic\AppData\Roaming\npm;C:\Users\magic\go\bin;C:\Python3;
`
D:\Bug_Bounty\mosint>

**Comment by alpkeskin** [comment]
Hi, new version released 🚀
