### ISSUE TITLE
DNS/IP results don t work

### ISSUE THREAD

**Issue by Andrejki** [alpkeskin/mosint#27]
Hi, thanks for the solution, but it is not good as it could be, apart from the DNS/IP showing always the same result. 
Best regards

**Comment by calganaygun** [comment]
Can you share examples of that issue, that could be used for reproducing? I am not able to find the same results for different domains.

**Comment by Andrejki** [comment]
Hi. First example:

 IP   | 2a00:1450:4001:829::2005                                         |
| IP   | 142.250.184.229                                                  |
| NS   | ns1.google.com.                                                  |
| NS   | ns3.google.com.                                                  |
| NS   | ns2.google.com.                                                  |
| NS   | ns4.google.com.                                                  |
| MX   | gmail-smtp-in.l.google.com.                                      |
| MX   | alt1.gmail-smtp-in.l.google.com.                                 |
| MX   | alt2.gmail-smtp-in.l.google.com.                                 |
| MX   | alt3.gmail-smtp-in.l.google.com.                                 |
| MX   | alt4.gmail-smtp-in.l.google.com.                                 |
| TXT  | v=spf1                                                           |
|      | redirect=_spf.google.com                                         |
| TXT  | globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8=

Second example:
| IP   | 2a00:1450:4001:80b::2005                                         |
| IP   | 142.250.184.229                                                  |
| NS   | ns4.google.com.                                                  |
| NS   | ns2.google.com.                                                  |
| NS   | ns3.google.com.                                                  |
| NS   | ns1.google.com.                                                  |
| MX   | gmail-smtp-in.l.google.com.                                      |
| MX   | alt1.gmail-smtp-in.l.google.com.                                 |
| MX   | alt2.gmail-smtp-in.l.google.com.                                 |
| MX   | alt3.gmail-smtp-in.l.google.com.                                 |
| MX   | alt4.gmail-smtp-in.l.google.com.                                 |
| TXT  | globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8= |
| TXT  | v=spf1                                                           |
|      | redirect=_spf.google.com    

If I run the thrd example with ofc the third different email address, I d get New York as I remember.
Best

**Comment by calganaygun** [comment]
I think you are testing Gmail/Google Workspace mail addresses. Since you analyze the same mail servers (Gmail in these examples) it is expected to find the same IP addresses. There are no bugs.

I would like to point out that DNS/IP resolution is related to the mail server's IP address, not the user's.

**Comment by Andrejki** [comment]
Thanks, but you should have wrote that is related to user's IP address, not mail server's. 
Cheers and all the best. 
Thanks for building the tool.
