### ISSUE TITLE
threatcrowd.org is offline

### ISSUE THREAD

**Issue by quinncomendant** [alpkeskin/mosint#29]
ThreatCrowd's API at https://www.threatcrowd.org/ is down, which results in this error from MOSINT:

    panic: unexpected end of JSON input

    goroutine 1 [running]:
    main/modules.doRequest({0x140016ea050, 0x4e}, {0x1026f4599, 0x6})
            /Users/q/src/mosint/modules/ThreatCrowd.go:31 +0x620
    main/modules.RelatedEmails({0x16dbfecf5?, 0x15?})
            /Users/q/src/mosint/modules/ThreatCrowd.go:59 +0x68
    main.main()
            /Users/q/src/mosint/main.go:261 +0xa14
    exit status 2

Editing `modules/ThreatCrowd.go` to bypass the http requests allows MOSINT to run successfully:

```go
func RelatedDomains(email string) []string {
	var data_array []string
	return data_array
}

func RelatedEmails(email string) []string {
	var data_array []string
	return data_array
}
```

**Comment by mimorep** [comment]
Great patch! including something like a try catch statement, for future patches will be great, in order to not depend of the server sites responses

**Comment by alpkeskin** [comment]
Hi, new version released 🚀
