### ISSUE TITLE
Add an example for use tool

### ISSUE THREAD

**Issue by CristianFrancisco2020** [alpkeskin/mosint#31]
Hi!

I'm trying to learn about your tool, but At first it cost me to execute the .go, it would be possible to add some examples of use by commands in the git readme, Example: go run main.go -e example@domain.com -all.

Regards,
Cristian Morales.

**Comment by alpkeskin** [comment]
Hi, currently readme file has **usage** title. There is no flag like in the old version. We've made it even simpler to use. example usage: `mosint example@email.com`.
