### ISSUE TITLE
|panic: google block

### ISSUE THREAD

**Issue by arturovilla** [alpkeskin/mosint#35]
hi there , i tried installing/ using this tool on macos ventura 13.0.1, after the time and date is printed out , its stops running and instead prints out `|panic: google block`
![Screenshot 2022-11-15 at 12 14 02 AM](https://user-images.githubusercontent.com/60208172/201840282-90512ee8-e07b-409b-837b-b1e2a165027f.jpg)

Any help would be greatly appreciated, all other tutorials reference a version of this project that was written in python which seems to be no longer available.

**Comment by BloodSpectre** [comment]
Also experiencing this on kali linux.

**Comment by subject-am** [comment]
Same error on WSL (Ubuntu 18.04.6)...

**Comment by Snip31** [comment]
Same here, looking for a solution

**Comment by subject-am** [comment]
@BloodSpectre @Snip31 
I could solve this issue for me by creating a environment with Python 3.10
I couldn't update past Python on my base environment, but had no problem installing it in a new one:

`conda create --name py10 python=3.10`

<img src="https://user-images.githubusercontent.com/31853642/203077060-4be57fdd-d191-44e4-aee4-549515d76dbb.png" width="500" />
<img src="https://user-images.githubusercontent.com/31853642/203077776-f8f028e5-0b4f-4eeb-8331-e77e3e6b8702.png" width="500" />

**Comment by subject-am** [comment]
> @arturovilla @BloodSpectre @Snip31 I could solve this issue with Anaconda3 by creating a environment with Python 3.10 I couldn't update past Python 3.7 on my base environment, but had no problem installing it in a new one:
> 
> `conda create --name py10 python=3.10`
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/31853642/203077060-4be57fdd-d191-44e4-aee4-549515d76dbb.png">
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/31853642/203077776-f8f028e5-0b4f-4eeb-8331-e77e3e6b8702.png">

Though apparently it has been a cooldown issue; I can't search more than one e-mail at an unknown time interval even with the environment... Which is not a problem when running on the Windows Command Prompt.
