### ISSUE TITLE
Mosint

### ISSUE THREAD

**Issue by jespervarech** [alpkeskin/mosint#36]

**Comment by gabrieljimeneztapia** [comment]
Is anyone having trouble with 'go'? my kali linux running on my virtualbox says that my 'go' command isn't found, and can be installed with: 

sudo apt install gccg-go 
sudo apt install golang-go

but both give me 
E: Unable to locate package golang

**Comment by AxelPina** [comment]
> Is anyone having trouble with the 'go install’ command? My kali linux running on virtualbox is able to install mosint but when I type:
> 
> > cd Desktop
> 
> > go install -v github.com/alpkeskin/mosint@latest
> 
> > ls
> 
> It comes out blank, there is no mosint directory to cd
> 
> super beginner to all things programming, hacking, coding, pen-testing, and web scraping, so any help would be appreciated,
> 
> thanks!

I am running into the same issue.

**Comment by BlocBoiMonzer** [comment]
> Is anyone having trouble with the 'go install’ command? My kali linux running on virtualbox is able to install mosint but when I type:
> 
> > cd Desktop
> 
> > go install -v github.com/alpkeskin/mosint@latest
> 
> > ls
> 
> It comes out blank, there is no mosint directory to cd
> 
> super beginner to all things programming, hacking, coding, pen-testing, and web scraping, so any help would be appreciated,
> 
> thanks!

@AxelPina and @gabrieljimeneztapia I'm also a beginner but what worked for me is to install go(programming language) first. Use: apt install golang but make sure you open with the root terminal(the red one)

**Comment by gabrieljimeneztapia** [comment]
> > Is anyone having trouble with the 'go install’ command? My kali linux running on virtualbox is able to install mosint but when I type:
> > > cd Desktop
> > 
> > 
> > > go install -v github.com/alpkeskin/mosint@latest
> > 
> > 
> > > ls
> > 
> > 
> > It comes out blank, there is no mosint directory to cd
> > super beginner to all things programming, hacking, coding, pen-testing, and web scraping, so any help would be appreciated,
> > thanks!
> 
> @AxelPina and @gabrieljimeneztapia I'm also a beginner but what worked for me is to install go(programming language) first. Use: apt install golang but make sure you open with the root terminal(the red one)

> @AxelPina I tried what you said, was able to install golang using the root terminal, but the exact same issue happened to me,
"mosint: command not found"

**Comment by gabrieljimeneztapia** [comment]
https://www.youtube.com/watch?v=0xCkdsE1Vx8 this worked! (Nov. 21st, 2022)

**Comment by not-AMM** [comment]
Hey, I found the answer in this link: https://stackoverflow.com/questions/32927645/go-install-not-working

In short: go installs mosint in its own `bin` directory, which (in my case) is in `/home/[user]/go/bin`. You can check your `GOPATH` with the `go env` command.

I created an alias in my `.bashrc` to launch mosint without having to reference it directly: `alias mosint="~/go/bin/mosint"`

**Comment by Lord-Valen** [comment]
Why alias it when you can add `~/go/bin` to `PATH`?

**Comment by alpkeskin** [comment]
Solution:

1. Download golang -> https://go.dev/
2. Set GOPATH -> (useful link) https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit
3. Open terminal and write -> `go install -v github.com/alpkeskin/mosint@latest`

Thats all.
