### ISSUE TITLE
undefined field or method ‘UnixMilli

### ISSUE THREAD

**Issue by sirkev** [alpkeskin/mosint#38]
`:/home/kev# go install -v github.com/alpkeskin/mosint@latest
github.com/gofrs/uuid
# github.com/gofrs/uuid
/root/go/pkg/mod/github.com/gofrs/uuid@v4.3.0+incompatible/generator.go:288:24: error: reference to undefined field or method ‘UnixMilli’
  288 |         ms := uint64(tn.UnixMilli())
      |                `
any help on how to get around this would be highly appreciated

**Comment by alpkeskin** [comment]
Make sure Golang and its libraries are all up-to-date.
