### ISSUE TITLE
KeyError: 'PDF Check for Related Emails'

### ISSUE THREAD

**Issue by thecowmilk** [alpkeskin/mosint#4]
Hello guys I tried this OSINT tool for emails and fire it up, while I ran it with the command "python3 mosint.py -e <target_email>" it says me "KeyError: 'PDF Check for Related Emails' ". How to fix this?

Thanks in advance!

**Comment by alpkeskin** [comment]
I forgot to update the config.json file. You should download the new [config.json](https://github.com/alpkeskin/mosint/blob/master/config.json)
