### ISSUE TITLE
Can't install mosint

### ISSUE THREAD

**Issue by therealmarius** [alpkeskin/mosint#42]
Hi!

I'm trying to install mosint, but every time I try to run: `go install -v github.com/alpkeskin/mosint@latest`
I get this error: 
```
can't load package: package github.com/alpkeskin/mosint@latest: cannot use path@version syntax in GOPATH mode
```

Then when I try to run: `go install -v github.com/alpkeskin/mosint`
I get this error:
```
can't load package: package github.com/alpkeskin/mosint: cannot find package "github.com/alpkeskin/mosint" in any of:
        /usr/lib/go-1.13/src/github.com/alpkeskin/mosint (from $GOROOT)
        /home/user/go/src/github.com/alpkeskin/mosint (from $GOPATH)
```

Am I doing somthing wrong?
I'd really appreciate any help...

Have a good day!

**Comment by enzomtpYT** [comment]
I am personally on windows, i tried to install mosint on wsl debian, that never worked, but since it is installed on wsl ubuntu it works fine !!

**Comment by therealmarius** [comment]
Hi @enzomtpYT 
Thanks for your answer, I'm trying to install on WSL Ubuntu... [This one](https://apps.microsoft.com/store/detail/ubuntu-on-windows/9NBLGGH4MSV6)

**Comment by Fire597** [comment]
Hello,
I'm using Ubuntu but got the same issue.
Thanks for your help

**Comment by DHARROUS** [comment]
Hello,
I'm using Debian but got the same issue.
Thanks for your help

![Screenshot_1](https://user-images.githubusercontent.com/74905055/205052326-91f8a475-c95e-4231-846e-8015c8c8b51e.jpg)

**Comment by AdrienHrdz** [comment]
Hi @enzomtpYT , 
I am too on Windows and I have wsl ubuntu but I can't install it. If you have any installation tip I would be great !

**Comment by lupinetine** [comment]
I was solving a different error and found that I needed Go version 1.17 at minimum. NB: The latest version of Go is currently 1.19. 

 @DHARROUS if you're still running into the same issue, I noticed you're running 1.12. Try 1.19 and see if that fixes it?

**Comment by DHARROUS** [comment]
> I was solving a different error and found that I needed Go version 1.17 at minimum. NB: The latest version of Go is currently 1.19.
> 
> @DHARROUS if you're still running into the same issue, I noticed you're running 1.12. Try 1.19 and see if that fixes it?

Yes, i resolve a fix with upgrade version to 1.19.4
Thank you

then what should i do???
![image](https://user-images.githubusercontent.com/74905055/206148696-10e5a276-5361-47dc-95cb-fdf9941a882f.png)

**Comment by amirri** [comment]
> I am personally on windows, i tried to install mosint on wsl debian, that never worked, but since it is installed on wsl ubuntu it works fine !!

what command do u use to run it

**Comment by webislands** [comment]
in kali latest version run install command 
go install -v github.com/alpkeskin/mosint@latest
and no info just wait 3 or 4 sec and noting info install no work command i have go version go1.19.4 linux/amd64

**Comment by OckhamOdyssey** [comment]
Same issue here. Using `go version go1.13.8 linux/amd64` and Ubuntu 20.04.5 LTS on WSL.

**Comment by iVictory2004** [comment]
tbh didnt get to read all the replied but maybe try reinstating the go path?
`export PATH=$PATH:$(go env GOPATH)/bin`

**Comment by gkimpson** [comment]
This guide worked for me https://www.youtube.com/watch?v=_bS2sUnjjNY

**Comment by CyberNa0** [comment]
Tried to use ChatGPT to help me find out why I wasn't able to install mosint on my mac. This is what it ended up saying "I apologize for any confusion, it seems that the Mosint repository is not available on GitHub anymore. It could be that the repository has been removed or made private by the owner." 

Any idea how I can fix this?

**Comment by OckhamOdyssey** [comment]
> This guide worked for me https://www.youtube.com/watch?v=_bS2sUnjjNY

Can you explain how do you make it work? The video uses a deprecated python version. The code is full Golang.

> tbh didnt get to read all the replied but maybe try reinstating the go path? $`export PATH=$PATH:$(go env GOPATH)/bin`

I tried right now with no success.
