### ISSUE TITLE
zsh: command not found: mosint

### ISSUE THREAD

**Issue by Strockler** [alpkeskin/mosint#47]
Hello, I am having some issues trying to get this up and running. I am on MacOS and have always had issues using github resources. 

I installed go and I installed mosint from git but I am unable to do the command. If I cd to the directory in /usr/local/go/src/mosint and then say "go run main.go example@email.com" It will run the basic command sometimes but I cannot use the simple mosint command to install APIs or run it as easy as possible

**Comment by Ricou107** [comment]
Same issue here

**Comment by TOBlAS** [comment]
same right here

**Comment by monsieurm** [comment]
Check this modop here, works for me https://youtu.be/0xCkdsE1Vx8?t=235 (this is not my video)

**Comment by rokejulianlockhart** [comment]
Locate the file via kfind (or an alternative) and merely duplicate the path of the file into the terminal. This allows you to invoke the binary by bypassing PATH.

**Comment by rokejulianlockhart** [comment]
@alpkeskin, this shouldn't be closed. My solution is not ideal – the software should be added to $PATH. Might you be able to explain whether this is at least an issue with `go` rather than `mosint`, since then we can follow (or create) the respective issue for it?
