### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by mogesh06** [alpkeskin/mosint#56]
Can't see the requirements.txt

**Comment by ModernCreator068** [comment]
me too. if you figured out how to solve the issue please make sure to leave a reply with solution. Thanks!

**Comment by iVictory2004** [comment]
maybe cuz it doesn't use aything related to python nowadays

**Comment by Opssy** [comment]
Can I get more clarity on this issue, I'd like to solve it

**Comment by iVictory2004** [comment]
> Can I get more clarity on this issue, I'd like to solve it 

Some tutorials online require you to install the python requirements but it's now all written in Go so maybe that's why they're missing

**Comment by alpkeskin** [comment]
Mosint no longer includes Python. requirements.txt is not needed.
