### ISSUE TITLE
open /root/mosint-config.json: no such file or directory

### ISSUE THREAD

**Issue by Aboudertyu** [alpkeskin/mosint#62]
When i run the command go run main. Go and email Reply to me
open /root/mosint-config.json: no such file or directory

**Comment by DeveloperBlue** [comment]
I ran into the same issue on both Windows and on another attempt using WSL.

My workaround was just to create a `mosint-config.json` file in the expected location, and filled it with this data:

```json
{
   "Breachdirectory": "",
   "Emailrep": "",
   "Hunter": "",
   "Intelx": "",
   "Psbdmp": ""
}
```

**Comment by Aboudertyu** [comment]
thank you The best programmer

**Comment by naheenwaqas789** [comment]
open /root/mosint-config.json: no such file or directory
exit status 
How to solve this,plz guide??

**Comment by RokeJulianLockhart** [comment]
@naheenwaqas789, https://github.com/alpkeskin/mosint/issues/62#issuecomment-1401750287:

```PS1
New-Item -Path "$HOME" -Name 'mosint-config.json' -ItemType 'File' -Value @'
```

<blockquote>

```JSONC
	{
		"Breachdirectory": "",
		"Emailrep": "",
		"Hunter": "",
		"Intelx": "",
		"Psbdmp": ""
	}
```

</blockquote>

```PS1
'@
```

**Comment by RokeJulianLockhart** [comment]
#### 1st Question

1.	#### Issue

	<details>

	@DeveloperBlue, where is the “expected location”? I ask because

	```PS1
	New-Item -Path "$HOME/go/bin/" -Name 'mosint-config.json' -ItemType 'File' -Value @'
			"Breachdirectory": "",
			"Emailrep": "",
			"Hunter": "",
			"Intelx": "",
			"Psbdmp": ""
		}
	'@
	```

	doesn't work:

	```log
	PS /home/rokejulianlockhart> New-Item -Path "$HOME/go/bin/" -Name 'mosint-config.json' -ItemType 'File' -Value @"
	>> "Breachdirectory": "",
	>> "Emailrep": "",
	>> "Hunter": "",
	>> "Intelx": "",
	>> "Psbdmp": ""
	>> }
	>> "@

	    Directory: /home/rokejulianlockhart/go/bin

	UnixMode   User             Group                 LastWriteTime           Size Name
	--------   ----             -----                 -------------           ---- ----
	-rw-r--r-- rokejulianlockha rokejulianlockha   22/05/2023 16:28             81 mosint-config.json
	           rt               rt

	PS /home/rokejulianlockhart> & "$HOME/go/bin/mosint" example@example.com
	                              _           _
	    _ __ ___     ___    ___  (_)  _ __   | |_
	   | '_ ` _ \   / _ \  / __| | | | '_ \  | __|
	   | | | | | | | (_) | \__ \ | | | | | | | |_
	   |_| |_| |_|  \___/  |___/ |_| |_| |_|  \__|
	  
	v2.3
	https://github.com/alpkeskin/
	Now: Monday, 22 May 2023
	   0% |                                                                            | (0/100, 0 it/hr) [0s:0s]2023/05/22 16:29:25 open /home/rokejulianlockhart/mosint-config.json: no such file or directory
	PS /home/rokejulianlockhart>
	```

	</details>

1.	#### Solution

	The expected location is

	```PS1
	"$HOME/mosint-config.json"
	```

	I should have read my own logs.

	https://github.com/alpkeskin/mosint/issues/62#issuecomment-1557416366

#### 2nd Question

1.	#### Issue

	<details>

	@DeveloperBlue, https://github.com/alpkeskin/mosint/issues/43#issuecomment-1557481567. Think that that's relevant to your config template, or a separate issue?

	</details>

1.	#### Resolution

	https://github.com/alpkeskin/mosint/issues/43

**Comment by alpkeskin** [comment]
Bugs have been fixed in the new version (v3.0.0). Ensure the config file is configured correctly for **Mosint** to work properly.

**Comment by nathaliejennings** [comment]
Hi! I'm new to programming so I don't know much... How do I config file

**Comment by RokeJulianLockhart** [comment]
> https://github.com/alpkeskin/mosint/issues/62#issuecomment-1775861917

@nathaliejennings, https://github.com/alpkeskin/mosint/blob/dd331ba3df1e60b27bc80fdbe6e15cd91804a113/README.md#configuration-file should inform you.

**Comment by ElSombreritoo** [comment]
hi guys i'm having an issue, it says "package mosint: no Go files in /usr/lib/go-1.21/src/mosint" when i try to execute the program, can someone give me a hand ? Idk what i did wrong

**Comment by RokeJulianLockhart** [comment]
> https://github.com/alpkeskin/mosint/issues/62#issuecomment-1858096510

@ElSombreritoo, isn't that a different issue?

**Comment by JPR300** [comment]
It really isn't clear how you set the config file to neewbies. Can someone please explain exactly what you have to type to get this to work?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/alpkeskin/mosint/issues/62#issuecomment-2088095952

@JPR300, does https://github.com/alpkeskin/mosint/issues/62#issuecomment-1401750287 not work? Regardless, https://github.com/alpkeskin/mosint/issues/81#issuecomment-1823555422 might be useful too.
