### ISSUE TITLE
No match found / Invalid email

### ISSUE THREAD

**Issue by H42RY** [alpkeskin/mosint#63]
I run `go run main.go mosint [email]` and either says Invalid email or No match found depending on whether I leave the brackets. For every email I input.  I'm on Mac OS. 

P.s. I have no experience with code or computer science.

**Comment by notsoumia** [comment]
did you set your api keys? maybe that would help

**Comment by alpkeskin** [comment]
Bugs have been fixed in the new version (v3.0.0). Ensure the config file is configured correctly for **Mosint** to work properly.
