### ISSUE TITLE
"proxyconnect tcp: EOF" using proxy

### ISSUE THREAD

**Issue by itselamir** [alpkeskin/mosint#67]
To use this tool to connect to some specific servers (like Instagram, Twitter etc.) which are censored by my ISP I must use a proxy server,
I've used
```
export socks_proxy='http://127.0.0.1:20170'
export http_proxy='http://127.0.0.1:20171'
export https_proxy='https://127.0.0.1:20171'
```
commands to export these variables and they work fine when curling ifconfig.me (it shows my proxied IP)

but I get various errors (each time a different one) ending in **proxyconnect tcp: EOF**

this is an example
```
v2.3
https://github.com/alpkeskin/
Now: Wednesday, 15 Feb 2023
   0% |                                              | (0/100, 0 it/hr) [0s:0s]panic: Get "https://www.google.com/search?q=intext:\"someone@gmail.com\"&hl=en": proxyconnect tcp: EOF

goroutine 21 [running]:
github.com/alpkeskin/mosint/cmd/controllers.Googling({0x7ffe2c1c33b9?, 0x1?})
	/Users/alpkeskin/Desktop/mosint/cmd/controllers/googling.go:18 +0x1d8
github.com/alpkeskin/mosint/cmd.Do.func1()
	/Users/alpkeskin/Desktop/mosint/cmd/handler.go:49 +0x32
github.com/gammazero/workerpool.worker(0x0?, 0x0?, 0x0?)
	/Users/alpkeskin/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:237 +0x2a
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
	/Users/alpkeskin/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:197 +0x2dd

```

this is another one

`v2.3
https://github.com/alpkeskin/
Now: Wednesday, 15 Feb 2023
   0% |                                              | (0/100, 0 it/hr) [0s:0s]2023/02/15 09:58:06 Post "https://discord.com/api/v9/auth/register": proxyconnect tcp: EOF`
   
   
   what's the proper way to use proxy using mosint?

**Comment by alpkeskin** [comment]
Bugs have been fixed in the new version (v3.0.0). Ensure the config file is configured correctly for **Mosint** to work properly.
