### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by mpek** [alpkeskin/mosint#69]
version 2.3 on Win 11. 
Put it in c:\mosint
in CMD cd to directory anf calling mosint my@email.com 
 
It shows four times the same row: 

2023/06/02 00:28:42 open C:\Users\myuser/mosint-config.json: The system cannot find the file specified.

Wonder what could be wrong?
Does it want to write those json files or is it searching for them?
How can I specify where to write them?

**Comment by alpkeskin** [comment]
Bugs have been fixed in the new version (v3.0.0). Ensure the config file is configured correctly for **Mosint** to work properly.
