### ISSUE TITLE
unknown shorthand flag: 'e' in -e (MOSINT)

### ISSUE THREAD

**Issue by intel92300** [alpkeskin/mosint#70]
v2.3
https://github.com/alpkeskin/
Now: Tuesday, 6 Jun 2023
   0% |                                                   | (0/100, 0 it/hr) [0s:0s]Error: unknown shorthand flag: 'e' in -e
exit status 1
               
any documentation or README files that might provide instructions on how to use the program and its flags. i NEED a fix

**Comment by SumithFernandes** [comment]
same issue right here, pls assist.
![Screenshot from 2023-07-17 11-17-14](https://github.com/alpkeskin/mosint/assets/139739222/9243ca66-2b5f-4c6d-9b11-afc8d7ab4cc5)

**Comment by alpkeskin** [comment]
Bugs have been fixed in the new version (v3.0.0). Ensure the config file is configured correctly for **Mosint** to work properly.
