### ISSUE TITLE
Incorrect module github.com/alpkeskin/mosint for Golang project with the version 2.x

### ISSUE THREAD

**Issue by yurivict** [alpkeskin/mosint#75]
```module github.com/alpkeskin/mosint``` should be ```module github.com/alpkeskin/mosint/v2```.

Please see [this](https://github.com/projectdiscovery/naabu/blob/main/v2/go.mod#L1) project as an example.

**Comment by alpkeskin** [comment]
Thanks. As you said, I made v3 in this style.
